import type { Meta, StoryObj } from "@storybook/react";
import styles from "./guidelines.module.css";

function DesignPrinciplesPage() {
  return (
    <div className={styles.page}>
      <h1 className={styles.pageTitle}>Design Principles</h1>
      <p className={styles.pageDescription}>
        These principles guide every decision in the Atelier Design System --
        from token definitions to component APIs to pattern composition.
      </p>

      <h2 className={styles.sectionTitle}>1. Tokens are the constraint</h2>
      <p className={styles.body}>
        If a value is not in the token set, it does not exist. Components
        reference CSS variables generated by Style Dictionary, never hardcoded
        colors, sizes, or spacing. This guarantees visual consistency and makes
        theming automatic.
      </p>

      <h2 className={styles.sectionTitle}>2. Own the platform</h2>
      <p className={styles.body}>
        Every component is built on native HTML elements and browser APIs. No
        UI library dependencies. This means the system has zero black boxes --
        every ARIA attribute, keyboard handler, and focus behavior is visible,
        testable, and documented.
      </p>

      <h2 className={styles.sectionTitle}>3. Accessible by default, not by opt-in</h2>
      <p className={styles.body}>
        Accessibility is built into the component, not exposed as a prop the
        consumer might forget. A Switch always has <span className={styles.code}>role="switch"</span>.
        A Dialog always traps focus. A Button always has <span className={styles.code}>type="button"</span>.
        Consumers cannot accidentally ship an inaccessible instance.
      </p>

      <h2 className={styles.sectionTitle}>4. Composition over configuration</h2>
      <p className={styles.body}>
        Complex components use compound component APIs (children + Context)
        rather than monolithic prop objects. This gives consumers control over
        markup while the system manages state and keyboard behavior. A consumer
        should never hit a wall where the API cannot express what they need.
      </p>
      <div className={styles.grid}>
        <div className={styles.do}>
          <div className={styles.doLabel}>Do</div>
          <div className={styles.codeBlock}>{`<AtelierAccordion>
  <AtelierAccordionItem value="faq">
    <AtelierAccordionTrigger>
      <Icon /> Question
    </AtelierAccordionTrigger>
    <AtelierAccordionContent>
      Answer with <a href="#">links</a>
    </AtelierAccordionContent>
  </AtelierAccordionItem>
</AtelierAccordion>`}</div>
        </div>
        <div className={styles.dont}>
          <div className={styles.dontLabel}>Don't</div>
          <div className={styles.codeBlock}>{`<AtelierAccordion
  items={[{
    title: "Question",
    content: "Answer"
  }]}
/>`}</div>
        </div>
      </div>

      <h2 className={styles.sectionTitle}>5. Explicit over clever</h2>
      <p className={styles.body}>
        Prefer readable, explicit code over abstractions that save keystrokes
        but hide behavior. Variant classes are plain <span className={styles.code}>Record</span> objects,
        not a CVA call. Styles are CSS files, not template literals. Hooks are
        named after what they do (<span className={styles.code}>useFocusTrap</span>), not what
        pattern they implement.
      </p>

      <h2 className={styles.sectionTitle}>6. Test behavior, not implementation</h2>
      <p className={styles.body}>
        Tests assert what the user experiences: Can they activate a button with
        the keyboard? Does the accordion announce its state to screen readers?
        Does the dialog trap focus? Tests never assert class names, internal
        state, or implementation details.
      </p>

      <h2 className={styles.sectionTitle}>7. One source of truth per concern</h2>
      <ul className={styles.list}>
        <li>Colors, spacing, typography -- <span className={styles.code}>tokens/*.json</span></li>
        <li>CSS variables -- generated by Style Dictionary (never hand-written)</li>
        <li>Component behavior -- the component file (no behavior in CSS)</li>
        <li>Component styling -- the CSS Module file (no styles in JSX)</li>
        <li>Usage documentation -- Storybook stories</li>
      </ul>
    </div>
  );
}

const meta: Meta = {
  title: "Guidelines/Design Principles",
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {
  render: () => <DesignPrinciplesPage />,
};
