import type { Meta, StoryObj } from "@storybook/react";
import styles from "./foundations.module.css";

function ColorSwatch({ name, variable, value }: { name: string; variable: string; value: string }) {
  return (
    <div className={styles.swatch}>
      <div className={styles.swatchColor} style={{ backgroundColor: value }} />
      <div className={styles.swatchLabel}>
        <span className={styles.swatchName}>{name}</span>
        <span className={styles.swatchValue}>{variable}</span>
      </div>
    </div>
  );
}

function ColorsPage() {
  return (
    <div className={styles.page}>
      <h1 className={styles.pageTitle}>Colors</h1>
      <p className={styles.pageDescription}>
        Color tokens are defined per-brand in JSON and generated by Style Dictionary.
        Switching brands or themes swaps the underlying CSS variables -- components
        adapt automatically.
      </p>

      <h2 className={styles.sectionTitle}>Core</h2>
      <div className={styles.swatchGrid}>
        <ColorSwatch name="Background" variable="--color-background" value="var(--color-background)" />
        <ColorSwatch name="Foreground" variable="--color-foreground" value="var(--color-foreground)" />
        <ColorSwatch name="Primary" variable="--color-primary" value="var(--color-primary)" />
        <ColorSwatch name="Primary Hover" variable="--color-primary-hover" value="var(--color-primary-hover)" />
        <ColorSwatch name="Secondary" variable="--color-secondary" value="var(--color-secondary)" />
        <ColorSwatch name="Destructive" variable="--color-destructive" value="var(--color-destructive)" />
      </div>

      <h2 className={styles.sectionTitle}>Surfaces</h2>
      <div className={styles.swatchGrid}>
        <ColorSwatch name="Card" variable="--color-card" value="var(--color-card)" />
        <ColorSwatch name="Popover" variable="--color-popover" value="var(--color-popover)" />
        <ColorSwatch name="Muted" variable="--color-muted" value="var(--color-muted)" />
        <ColorSwatch name="Accent" variable="--color-accent" value="var(--color-accent)" />
        <ColorSwatch name="Surface Elevated" variable="--color-surface-elevated" value="var(--color-surface-elevated)" />
      </div>

      <h2 className={styles.sectionTitle}>Text</h2>
      <div className={styles.swatchGrid}>
        <ColorSwatch name="Primary FG" variable="--color-primary-foreground" value="var(--color-primary-foreground)" />
        <ColorSwatch name="Secondary FG" variable="--color-secondary-foreground" value="var(--color-secondary-foreground)" />
        <ColorSwatch name="Muted FG" variable="--color-muted-foreground" value="var(--color-muted-foreground)" />
        <ColorSwatch name="Accent FG" variable="--color-accent-foreground" value="var(--color-accent-foreground)" />
        <ColorSwatch name="Subtle" variable="--color-subtle" value="var(--color-subtle)" />
      </div>

      <h2 className={styles.sectionTitle}>Borders & Interactive</h2>
      <div className={styles.swatchGrid}>
        <ColorSwatch name="Border" variable="--color-border" value="var(--color-border)" />
        <ColorSwatch name="Border Light" variable="--color-border-light" value="var(--color-border-light)" />
        <ColorSwatch name="Input" variable="--color-input" value="var(--color-input)" />
        <ColorSwatch name="Ring" variable="--color-ring" value="var(--color-ring)" />
        <ColorSwatch name="Warning" variable="--color-warning" value="var(--color-warning)" />
      </div>
    </div>
  );
}

const meta: Meta = {
  title: "Foundations/Colors",
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {
  render: () => <ColorsPage />,
};
