import Link from "next/link";
import styles from "../app-components/showcase.module.css";
import pageStyles from "./home.module.css";

export default function HomePage() {
  return (
    <div className={styles.page}>
      <h1 className={styles.pageTitle}>Atelier Design System</h1>
      <p className={styles.pageDescription}>
        A hand-rolled React design system built with CSS Modules and design
        tokens generated by Style Dictionary. Zero Radix, zero Tailwind, zero
        headless-UI libraries. Every primitive ships keyboard-navigable,
        screen-reader-friendly, and WAI-ARIA-compliant by default.
      </p>

      <div className={pageStyles.cta}>
        <Link href="/get-started" className={pageStyles.primaryLink}>
          Get started
        </Link>
        <Link href="/primitives/button" className={pageStyles.secondaryLink}>
          Browse primitives
        </Link>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>Foundations</h2>
        <p className={styles.sectionDescription}>
          Colors, typography, spacing, radius, shadows, motion, z-index, and
          breakpoints. All exposed as CSS custom properties, all themeable
          per-brand, all light and dark ready.
        </p>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>Primitives</h2>
        <p className={styles.sectionDescription}>
          Low-level UI building blocks: Button, Switch, Checkbox, TextField,
          Select, Tabs, Accordion, and Dialog. Each component follows WAI-ARIA
          authoring practices and supports controlled and uncontrolled usage.
        </p>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>Patterns</h2>
        <p className={styles.sectionDescription}>
          Higher-level compositions showing how primitives combine into
          real-world UI: form layouts, settings panels, and confirmation flows.
        </p>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>Guidelines</h2>
        <p className={styles.sectionDescription}>
          Accessibility expectations, keyboard interaction patterns, ARIA
          conventions, and the design principles that guide every decision in
          the system.
        </p>
      </div>
    </div>
  );
}
