import styles from "./page.module.css";
import showcase from "../../../app-components/showcase.module.css";

const principles = [
  {
    title: "Accessible by default",
    body: "Every component ships with correct ARIA roles, keyboard navigation, and focus management. Accessibility is not an afterthought -- it is a design constraint that shapes every API decision.",
  },
  {
    title: "Composable over configurable",
    body: "Primitives expose compound-component APIs so consumers can compose exactly the UI they need without fighting prop sprawl. Small, focused pieces combine into complex patterns.",
  },
  {
    title: "Token-driven",
    body: "Visual decisions live in design tokens, not in component code. Colours, spacing, typography, and radii are CSS custom properties generated by Style Dictionary, making themes and brands trivial to swap.",
  },
  {
    title: "Progressive disclosure",
    body: "Defaults should cover the common case. Advanced behaviour is available through optional props and composition, never forced on every consumer.",
  },
  {
    title: "Framework-agnostic styling",
    body: "CSS Modules and custom properties keep styles scoped, portable, and free of runtime overhead. No utility-class framework is required.",
  },
  {
    title: "Ship less, ship right",
    body: "A small set of well-tested, well-documented primitives is more valuable than a large set of half-finished ones. Quality gates include unit tests, axe audits, and visual regression checks.",
  },
];

export default function PrinciplesPage() {
  return (
    <div className={showcase.page}>
      <h1 className={showcase.pageTitle}>Design Principles</h1>
      <p className={showcase.pageDescription}>
        These principles guide every decision in the Atelier Design System,
        from API design to visual language.
      </p>

      <div className={styles.principles}>
        {principles.map((p) => (
          <div key={p.title} className={styles.card}>
            <h2 className={styles.cardTitle}>{p.title}</h2>
            <p className={styles.cardBody}>{p.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
